{% set version = "1.1.0" %}

package:
  name: mechanicalsoup
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/M/MechanicalSoup/MechanicalSoup-{{ version }}.tar.gz
  sha256: 2be8ad9b7571990fce16d0f99a741779921510eb133d3a4dfdeccb2ff2cd00e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - beautifulsoup4 >=4.7
    - lxml
    - requests >=2.22

test:
  imports:
    - mechanicalsoup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hickford/MechanicalSoup
  license: MIT
  license_file: LICENSE
  summary: A Python library for automating interaction with websites
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
