{% set name = "mechanicalsoup" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MechanicalSoup-{{ version }}.tar.gz
  sha256: f8593ab4474a82ceb6b7ddb3e35a8c69f8455a06adafd2b5258c1d852158d760

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests >=2.22.0
    - beautifulsoup4 >=4.7
    - lxml


test:
  imports:
    - mechanicalsoup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MechanicalSoup/MechanicalSoup
  license: MIT
  license_file: LICENSE
  summary: A Python library for automating interaction with websites
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
