{% set version = "0.7.0" %}

package:
  name: mechanicalsoup
  version: {{ version }}

source:
  fn: mechanicalSoup-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/M/MechanicalSoup/MechanicalSoup-{{ version }}.tar.gz
  sha256: 0d1523f8e14957d0cce1dae048ff35c4aabb4a2cbfd8014cbfd110426b1e0972

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests >=2.0
    - beautifulsoup4
    - six >=1.4

test:
  imports:
    - mechanicalsoup

about:
  home: https://github.com/hickford/MechanicalSoup
  license: MIT
  license_file: LICENSE
  summary: 'A Python library for automating interaction with websites'
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
