{% set version = "1.0.0" %}

package:
  name: mechanicalsoup
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/M/MechanicalSoup/MechanicalSoup-{{ version }}.tar.gz
  sha256: 37d3b15c1957917d3ae171561e77f4dd4c08c35eb4500b8781f6e7e1bb6c4d07

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - pytest-runner
  run:
    - python >=3.5
    - beautifulsoup4 >=4.4
    - lxml
    - requests >=2.0
    - six >=1.4

test:
  imports:
    - mechanicalsoup
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hickford/MechanicalSoup
  license: MIT
  license_file: LICENSE
  summary: A Python library for automating interaction with websites
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
