travis:
  secure:
    BINSTAR_TOKEN: ouaCgIXcTD3uxlcwqX6GFNSkeuSRy6n7FhogZhGNFpYWPNcLpBYtKqT+Hs89fsu4P6e2hGfUpB/n1/0c6g0XE4rtG4dN8UcP1BLupW5nBvEGeu9h80agNjkx1ex2j6kXGcz6djKNLbpV4XCq23dyBxmfmz/3R/J5MSib+dnaVhk8blFELjjScIoFgOfdOhsmmiQqLqrgaaRKSOg1IJjqTMlHwjMc19I2IrLdQStUP45SGpxLH6YTITw1QDBelKA/c8qiKLzJ8hZaqJxYpU82l5GsvK42tMW6AxL8AF76QeFkYNCr/TeuNf0UdXs/LCX3j1754wwPbCXt3dwuJizNlDKnMqTYdpZyF/HIzukFpLgGV5pRhDaeGPPffRCY8YVb9DEXgPWMDl5OD1DxUNr1yGhREKCnSXlU2YL0g4v57ki4bIbEGZeq+QycCrtkR2tJn0UvMt7vUP4wRachCNNZkbHw4viYBUJOvg4Fzoi7qDpln+dyGmSNY+CC6JDc2sUeUUgIaIh7gDRsU25yaTR7Wy2i6Q7NoIHi8lom0847hGxbQWpOhn6hJliBir3GAGVhoERH3UnGoLxzguvEeNwK5uxK5tGg8DpC580KrgQzHPM/AeVw5jn8nPh0G3vy6SJWTGZFRAIrgp+rinhD6cWs00lteDLNqzE2dB0l9DEk8ys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
