travis:
  secure:
    BINSTAR_TOKEN: qQWTnOFAOAca8Fu0mHB5W+IQ55l8A9WIJGwOajPxFbgDbbYO1l7aGxqL8x+TL2eMzb3cDZ+QDhBhSnA7MgqtP5zJHHV3EysZyKDeEvrxf2pKzXKGsdbBv9cro8lofm63k2lVs4SaqBCgjbQPVFkLZcwpr+j1IHWQaF0mloYt+BfDxNHMJXaGfj1yVGw+zegEFA9EpVlMrrFplHe1UHkyX9RvJT43X0HPxDNThrVYezYAv6RuNaPyh8omAA/RXwOT9SC/qfgnhZ8LiWNJkbhY8aDWVhiETD2pZtqApOVu+R8Y8NHVP+hYlNFaSmUKJXcXrpTTNvQ/nFfRuA6ljlMRV3TFT8JzJAMyNr4Sy9IhKVRucGDoJhsJNU3lf0cGIbZyJd/HSzfcE2djk9A5RLMyBpdHld6NTq9s3MAtOxllklSAWJzl4febLbuYOtFKpXVokQv3DgQqa5NvMe1eRFnMpllYpE4p/GlwgblpcCdfuIzgSKcc6dnsoHsODZNg81mfBduYNa/Kk65t/jDhKT/ZN/yima75zx9tJKfo+aOQ+F+2DLLi32gzc6wUQxQZjdaFAyXSo7kuwt9PaNczgyb1tT0izviESisKYo2CoCOwe1dFDFu298QjLkWpAEtvj/1AoWUT2RjD788FhMNls2iXUqviUmO5ITPY/03Bk/9ddOM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
